# Spring properties
spring:
  application:
     name: highway-services

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
  
neo4j:
 url: http://127.0.0.1:7474/db/data
 password: 
 user: 
 
highway:
  highwaypath: http://HIGHWAYPATH-SERVICES